version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_UID: 1000
                USER_GID: 1000

        ports:
            - '8081:8081'

        volumes:
            - ..:/workspace:cached

        command: sleep infinity
